# Project: D:\USR\code\able\public\testing\porting
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/cygwin/bin"  
INCS =  -I"C:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include/c++"  -I"C:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include/c++/i686-pc-cygwin/bits"  -I"D:/USR/code/mynoj/FastJob"  -I"D:/USR/code/able/public" 
CXXINCS =  -I"C:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include/c++"  -I"C:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4/include/c++/i686-pc-cygwin/bits"  -I"D:/USR/code/mynoj/FastJob"  -I"D:/USR/code/able/public" 
BIN  = porting.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)   
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before porting.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "porting.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
